
-- A SUPPRIMER EN PRODUCTION !!
--
DROP TABLE IF EXISTS "users",
"stories",
"blocks",
"levels",
"themes",
"saved_stories",
"choices"
CASCADE;
--
--
--

-- -----------------------------------------------------
-- Table users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mail" VARCHAR(64) NOT NULL,
  "firstname" VARCHAR(64) NOT NULL,
  "lastname" VARCHAR(64),
  "password" VARCHAR(128) NOT NULL,
  "avatar_path" VARCHAR(64),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table themes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "themes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "thumbnail_path" VARCHAR(128),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);
-- -----------------------------------------------------
-- Table levels
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "value" INT NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table stories
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "stories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(256) NOT NULL,
  "level_id" INT NOT NULL REFERENCES "levels"("id"),
  "theme_id" INT NOT NULL REFERENCES "themes"("id"),
  "thumbnail_path" VARCHAR(128) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table blocks
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "blocks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "story_id" INT NOT NULL REFERENCES "stories"("id"),
  "alphanum" VARCHAR(8) NOT NULL,
  "type" VARCHAR(8) NOT NULL,
  "label_text" VARCHAR(256),
  "choice_question" VARCHAR(256),
  "background_img_path" VARCHAR(128),
  "boy_character_img_path" VARCHAR(128) NOT NULL,
  "girl_character_img_path" VARCHAR(128) NOT NULL,
  "rest_img_path" VARCHAR(128),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz 
);

-- -----------------------------------------------------
-- Table choices
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "choices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "origin_block_id" INT NOT NULL REFERENCES "blocks"("id"),
  "destination_block_id" INT NOT NULL REFERENCES "blocks"("id"),
  "choice_label" VARCHAR(128),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "user_has_saved_stories"
-- -----------------------------------------------------
CREATE TABLE "saved_stories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id"),
  "story_id" INT NOT NULL REFERENCES "stories"("id"),
  "saved_story_name" VARCHAR(128),
  "is_story_finished" BOOLEAN NOT NULL,
  "block_progression" VARCHAR(8)[] NOT NULL,
  "character_gender" VARCHAR(8) NOT NULL,
  "character_name" VARCHAR(128),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);